@url = test.gedis2.cmd
name = ""
comment = ""
schemacode = ""

@url = test.gedis2.serverschema
@name = cmds
cmds = (LO) !test.gedis2.cmd

@url = test.gedis2.cmd1
@name = cmd
cmd = (O) !test.gedis2.cmd
cmd2 = (O) !test.gedis2.cmd

